package rodriguez.rosa.evangelion30.util

enum class NotificacionesUsuario {
    LOGIN_CORRECTO,
    LOGIN_INCORRECTO,
    REGISTRO_CORRECTO,
    REGISTRO_INCORRECTO,
    LOG_OUT,
    RESET_PASSWORD_CORRECTO,
    RESET_PASSWORD_INCORRECTO,

    //TAREA
    TAREA_AGREGADA_CON_EXITO,
    ERROR_AL_AGREGAR_TAREA,

    TAREA_EDITADA_CON_EXITO,
    ERROR_AL_EDITAR_TAREA

}